apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-server
  namespace: walle
spec:
  selector:
    matchLabels:
      app: api-server
  replicas: 1
  template:
    metadata:
      labels:
        app: api-server
    spec:
      containers:
        - name: api-server
          image: "yubinnng/walle-api-server"
          env:
            - name: POSTGRES_HOST
              value: postgres
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: postgres
            - name: NATS_URL
              value: nats.walle
            - name: ENGINE_URL
              value: http://gateway-external.openfaas:8080/function/walle-engine
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: api-server
  namespace: walle
spec:
  selector:
    app: api-server
  ports:
    - port: 8080